/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Agreement: typeof import('./src/components/agreement.vue')['default']
    Alert: typeof import('./src/components/alert.vue')['default']
    BulletChat: typeof import('./src/components/bullet-chat.vue')['default']
    Casecard: typeof import('./src/components/casecard.vue')['default']
    Empty: typeof import('./src/components/empty.vue')['default']
    Fixed: typeof import('./src/components/fixed/fixed.vue')['default']
    Form: typeof import('./src/components/form.vue')['default']
    Kefu: typeof import('./src/components/kefu.vue')['default']
    ListCell: typeof import('./src/components/list-cell/list-cell.vue')['default']
    MarkdownRenderer: typeof import('./src/components/MarkdownRenderer/MarkdownRenderer.vue')['default']
    Modal: typeof import('./src/components/modal.vue')['default']
    MyLoading: typeof import('./src/components/my-loading/my-loading.vue')['default']
    NetworkError: typeof import('./src/components/network-error/network-error.vue')['default']
    None: typeof import('./src/components/none.vue')['default']
    PopupClass: typeof import('./src/components/popupClass.vue')['default']
    PopupLayer: typeof import('./src/components/popup-layer/popup-layer.vue')['default']
    PromptBtm: typeof import('./src/components/promptBtm.vue')['default']
    Share: typeof import('./src/components/fixed/share.vue')['default']
    SubmitBottom: typeof import('./src/components/fixed/submitBottom.vue')['default']
    TextButton: typeof import('./src/components/fixed/textButton.vue')['default']
    UniIcons: typeof import('./src/components/uni-icons/uni-icons.vue')['default']
    UniPopup: typeof import('./src/components/uni-popup/uni-popup.vue')['default']
    UniSteps: typeof import('./src/components/uni-steps/uni-steps.vue')['default']
    UniTransition: typeof import('./src/components/uni-transition/uni-transition.vue')['default']
    WdButton: typeof import('wot-design-uni/components/wd-button/wd-button.vue')['default']
    WdGrid: typeof import('wot-design-uni/components/wd-grid/wd-grid.vue')['default']
    WdGridItem: typeof import('wot-design-uni/components/wd-grid-item/wd-grid-item.vue')['default']
    WdMessageBox: typeof import('wot-design-uni/components/wd-message-box/wd-message-box.vue')['default']
    WdPopup: typeof import('wot-design-uni/components/wd-popup/wd-popup.vue')['default']
    WdTag: typeof import('wot-design-uni/components/wd-tag/wd-tag.vue')['default']
    WdTextarea: typeof import('wot-design-uni/components/wd-textarea/wd-textarea.vue')['default']
    Webview: typeof import('./src/components/webview.vue')['default']
    WxShare: typeof import('./src/components/fixed/wxShare.vue')['default']
  }
}
