/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-components
// Read more: https://github.com/vuejs/core/pull/3399
export {}

declare module 'vue' {
  export interface GlobalComponents {
    Alert: typeof import('./components/alert.vue')['default']
    BaseCardBaseCard: typeof import('./components/BaseCard/BaseCard.vue')['default']
    BaseCardBaseItem: typeof import('./components/BaseCard/BaseItem.vue')['default']
    Casecard: typeof import('./components/casecard.vue')['default']
    Empty: typeof import('./components/empty.vue')['default']
    FixedFixed: typeof import('./components/fixed/fixed.vue')['default']
    FixedShare: typeof import('./components/fixed/share.vue')['default']
    FixedSubmitBottom: typeof import('./components/fixed/submitBottom.vue')['default']
    FixedTextButton: typeof import('./components/fixed/textButton.vue')['default']
    FixedWxShare: typeof import('./components/fixed/wxShare.vue')['default']
    Form: typeof import('./components/form.vue')['default']
    GlobalLoading: typeof import('./components/GlobalLoading.vue')['default']
    GlobalMessage: typeof import('./components/GlobalMessage.vue')['default']
    GlobalToast: typeof import('./components/GlobalToast.vue')['default']
    Kefu: typeof import('./components/kefu.vue')['default']
    MarkdownRenderer: typeof import('./components/MarkdownRenderer/index.vue')['default']
    MenuCell: typeof import('./components/MenuCell.vue')['default']
    NoLogin: typeof import('./components/NoLogin.vue')['default']
    None: typeof import('./components/none.vue')['default']
    OpenType: typeof import('./components/OpenType.vue')['default']
    PrivacyPopup: typeof import('./components/PrivacyPopup.vue')['default']
    PromptBtm: typeof import('./components/promptBtm.vue')['default']
    WdBadge: typeof import('wot-design-uni/components/wd-badge/wd-badge.vue')['default']
    WdButton: typeof import('wot-design-uni/components/wd-button/wd-button.vue')['default']
    WdCheckbox: typeof import('wot-design-uni/components/wd-checkbox/wd-checkbox.vue')['default']
    WdConfigProvider: typeof import('wot-design-uni/components/wd-config-provider/wd-config-provider.vue')['default']
    WdDivider: typeof import('wot-design-uni/components/wd-divider/wd-divider.vue')['default']
    WdGap: typeof import('wot-design-uni/components/wd-gap/wd-gap.vue')['default']
    WdGrid: typeof import('wot-design-uni/components/wd-grid/wd-grid.vue')['default']
    WdGridItem: typeof import('wot-design-uni/components/wd-grid-item/wd-grid-item.vue')['default']
    WdIcon: typeof import('wot-design-uni/components/wd-icon/wd-icon.vue')['default']
    WdLoading: typeof import('wot-design-uni/components/wd-loading/wd-loading.vue')['default']
    WdMessageBox: typeof import('wot-design-uni/components/wd-message-box/wd-message-box.vue')['default']
    WdNotify: typeof import('wot-design-uni/components/wd-notify/wd-notify.vue')['default']
    WdPopup: typeof import('wot-design-uni/components/wd-popup/wd-popup.vue')['default']
    WdStep: typeof import('wot-design-uni/components/wd-step/wd-step.vue')['default']
    WdSteps: typeof import('wot-design-uni/components/wd-steps/wd-steps.vue')['default']
    WdTab: typeof import('wot-design-uni/components/wd-tab/wd-tab.vue')['default']
    WdTabbar: typeof import('wot-design-uni/components/wd-tabbar/wd-tabbar.vue')['default']
    WdTabbarItem: typeof import('wot-design-uni/components/wd-tabbar-item/wd-tabbar-item.vue')['default']
    WdTabs: typeof import('wot-design-uni/components/wd-tabs/wd-tabs.vue')['default']
    WdTag: typeof import('wot-design-uni/components/wd-tag/wd-tag.vue')['default']
    WdToast: typeof import('wot-design-uni/components/wd-toast/wd-toast.vue')['default']
    Webview: typeof import('./components/webview.vue')['default']
    YpScrollView: typeof import('./components/YpScrollView.vue')['default']
    YpTag: typeof import('./components/YpTag.vue')['default']
  }
}
