/* eslint-disable */
/* prettier-ignore */
// @ts-nocheck
// Generated by vite-plugin-uni-pages

interface NavigateToOptions {
  url: "/pages/index/index" |
       "/pages/index/message" |
       "/pages/index/user" |
       "/pages/index/workplace" |
       "/pages/index/article/detail" |
       "/pages/index/article/more" |
       "/pages/index/components/SharePoster" |
       "/pages/index/components/TypicalCase" |
       "/pages/AI/chat" |
       "/pages/AI/components/Feedback" |
       "/pages/AI/components/HistoryDrawer" |
       "/pages/case/list" |
       "/pages/case/poster" |
       "/pages/case/components/StepsPopup" |
       "/pages/chat/chatroom" |
       "/pages/chat/files" |
       "/pages/chat/newCaseList" |
       "/pages/chat/components/casecard" |
       "/pages/chat/components/chatbar" |
       "/pages/chat/components/chatmsg" |
       "/pages/chat/components/invitepersonal" |
       "/pages/chat/components/teaminvite" |
       "/pages/chat/components/userTypes" |
       "/pages/team/list" |
       "/pages/team/qrcode" |
       "/pages/invite/inviteYou" |
       "/pages/invite/list" |
       "/pages/invite/components/InviteStatistics" |
       "/pages/invite/components/UpgradeTip" |
       "/pages/login/login" |
       "/pages/login/phoneLogin" |
       "/pages/login/components/Agreement" |
       "/pages/lpgs/apply" |
       "/pages/mcd/mcd-detail" |
       "/pages/mcd/mcd-list" |
       "/pages/mcd/ranking" |
       "/pages/mcd/components/activity-list" |
       "/pages/mcd/components/comment-list" |
       "/pages/meeting/verResult" |
       "/pages/meeting/verification" |
       "/pages/public/webview" |
       "/pages/public/y9net" |
       "/pages/public/agreement/privacyText" |
       "/pages/public/agreement/serviceText" |
       "/pages/user/userInfo" |
       "/pages/policy/fengshe" |
       "/pages/policy/sheyuan" |
       "/pages/policy/upgrade" |
       "/pages/news/detail" |
       "/pages/news/list" |
       "/pages/news/components/NewsCard" |
       "/pages/news/components/NewsPoster";
}
interface RedirectToOptions extends NavigateToOptions {}

interface SwitchTabOptions {
  url: "/pages/index/index" | "/pages/index/workplace" | "/pages/index/message" | "/pages/index/user"
}

type ReLaunchOptions = NavigateToOptions | SwitchTabOptions;

declare interface Uni {
  navigateTo(options: UniNamespace.NavigateToOptions & NavigateToOptions): void;
  redirectTo(options: UniNamespace.RedirectToOptions & RedirectToOptions): void;
  switchTab(options: UniNamespace.SwitchTabOptions & SwitchTabOptions): void;
  reLaunch(options: UniNamespace.ReLaunchOptions & ReLaunchOptions): void;
}
